### ISSUE TITLE
Permitted commands not appearing

### ISSUE THREAD

**Issue by rsimmons1127** [TjeuKayim/minecraft-command-permissions-fabric#2]
Once a permission has been granted, for example: minecraft.command.time, the command in not visible for autocomplete in the chat input. Running the command anyways is still successful, just never displayed when typing.

Using:
LuckPerms-Fabric-5.3.42
minecraft-command-permissions-1.0.2
fabric-permissions-api-v0.1
fabric-api-0.34.6+1.16

**Comment by TjeuKayim** [comment]
On our survival server we experience the same issue, thanks for reporting it.
I'm not sure how to fix this as `lucko/fabric-permissions-api` doesn't expose an API to handle permission updates. Do you know other Fabric mods that work with LuckPerms that do update autocompletion properly? This is probably something that LuckPerms should fix, as it is more efficient to send the updated autocomplete info to the client in one go for all mods that use the permissions API.

**Comment by rsimmons1127** [comment]
Thanks for the response. I am just getting started trying to work with LuckPerms, etc. so I'm not aware of another mod that would fix this but maybe its worth searching for. I agree LuckPerms should handle this if possible

**Comment by TjeuKayim** [comment]
I've implemented a fix in LuckPerms and opened a pull request as you can see above.
You could try this JAR or build my LuckPerms fork from source yourself.

[LuckPerms-Fabric-5.3-command-list-7f3610d9f2abc3494.jar.zip](https://github.com/TjeuKayim/minecraft-command-permissions-fabric/files/6623357/LuckPerms-Fabric-5.3-command-list-7f3610d9f2abc3494.jar.zip)
