### ISSUE TITLE
Conflict with MoreCommands mod

### ISSUE THREAD

**Issue by karstennn** [TjeuKayim/minecraft-command-permissions-fabric#4]
Title!

**Comment by karstennn** [comment]
I found that this mod conflicts with the more commands mod and that is why it was not working on 1.17.1 for me.

**Comment by TjeuKayim** [comment]
Thanks for reporting this incompatibility with MoreCommands. I have not used that mod myself, so I need some more details.

What did you try exactly (steps to reproduce)?
How did you expect it to work and for what purpose?
What was the actual behavior (did the server crash or something else)?

**Comment by karstennn** [comment]
I said the wrong mod, this mod is incompatible with the banhammer mod from https://www.curseforge.com/minecraft/mc-mods/patboxs-banhammer . I went through all of my mods individually and found that this was the only one it was incompatible with. The server would not start, I can upload the latest.log of it. I think this crashed because banhammer modifies the vanilla ban command, and I am assuming that is why it did not work. Thank you!

**Comment by TjeuKayim** [comment]
I took a quick look to the BanHammer source code, and saw it renames `ban` to `vanilla-ban`, and also `ban-ip`, `kick`, `pardon`. I guess that causes the compatibility issues.

The BanHammer commands already integrate with the permissions API using `banhammer.punish.*`. So, my mod 'minecraft-command-permissions' should either ignore the `ban` commands, or recognize that they are renamed to `vanilla-ban`. Another solution would be to have a config file with a `ignore_commands` array.

Does your server log shows the following error message?

```
[08:57:49] [main/FATAL] (Minecraft) Failed to start the minecraft server
 java.lang.NullPointerException: Cannot invoke "com.mojang.brigadier.tree.CommandNode.getRequirement()" because "child" is null
	at com.github.tjeukayim.commandpermissionsfabric.PermissionsMod.alterCommand(PermissionsMod.java:46) ~[main/:?]
	at com.github.tjeukayim.commandpermissionsfabric.PermissionsMod.lambda$onInitialize$1(PermissionsMod.java:34) ~[main/:?]
```

**Comment by karstennn** [comment]
Yes, my log says exactly that.

**Comment by TjeuKayim** [comment]
Can you try this new version I just released https://github.com/TjeuKayim/minecraft-command-permissions-fabric/releases/tag/v1.3.0
